-- =====================================================================
-- V1: core schema for BookMySeat
-- Money is BIGINT paise (never floats). user_id is TEXT because identity
-- comes from the auth token, there is no users table.
-- =====================================================================

-- ---------- shows ----------
CREATE TABLE shows (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT        NOT NULL,
    price_paise     BIGINT      NOT NULL CHECK (price_paise >= 0),
    per_user_limit  INT         NOT NULL DEFAULT 4 CHECK (per_user_limit > 0),
    total_seats     INT         NOT NULL CHECK (total_seats > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- reservations ----------
-- One row per successful booking. Kept after cancel (status flips) so an
-- idempotent replay can still return the original reservation.
CREATE TABLE reservations (
    id            UUID        PRIMARY KEY,                -- generated by the app
    show_id       UUID        NOT NULL REFERENCES shows (id),
    user_id       TEXT        NOT NULL,
    seats         TEXT[]      NOT NULL,
    amount_paise  BIGINT      NOT NULL CHECK (amount_paise >= 0),
    status        TEXT        NOT NULL CHECK (status IN ('confirmed', 'cancelled')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    cancelled_at  TIMESTAMPTZ,
    CONSTRAINT reservation_has_seats CHECK (cardinality(seats) > 0),
    CONSTRAINT cancelled_has_timestamp CHECK ((status = 'cancelled') = (cancelled_at IS NOT NULL))
);

CREATE INDEX idx_reservations_user_show ON reservations (user_id, show_id);

-- ---------- seats ----------
-- The row that decides who wins. The atomic grab is:
--   UPDATE seats SET status='confirmed', ... WHERE show_id=? AND label=? AND status='available'
-- and the number of rows updated (0 or 1) tells us if we won.
CREATE TABLE seats (
    show_id         UUID        NOT NULL REFERENCES shows (id),
    label           TEXT        NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'available'
                                CHECK (status IN ('available', 'held', 'confirmed')),
    user_id         TEXT,
    reservation_id  UUID,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (show_id, label),

    -- A seat is either free (no owner) or owned (user AND reservation set).
    -- The database itself refuses any half-state.
    CONSTRAINT seat_owner_consistent CHECK (
        (status = 'available' AND user_id IS NULL AND reservation_id IS NULL)
        OR
        (status <> 'available' AND user_id IS NOT NULL AND reservation_id IS NOT NULL)
    ),

    -- DEFERRED: checked at COMMIT, so a request can grab the seat first and
    -- insert its reservation row afterwards in the same transaction.
    CONSTRAINT fk_seat_reservation FOREIGN KEY (reservation_id)
        REFERENCES reservations (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_seats_show_status ON seats (show_id, status);
CREATE INDEX idx_seats_reservation ON seats (reservation_id) WHERE reservation_id IS NOT NULL;

-- ---------- per-user, per-show counter (for the booking limit) ----------
-- Guarded update: SET seat_count = seat_count + n WHERE seat_count + n <= limit
CREATE TABLE user_show_holdings (
    show_id     UUID NOT NULL REFERENCES shows (id),
    user_id     TEXT NOT NULL,
    seat_count  INT  NOT NULL DEFAULT 0 CHECK (seat_count >= 0),
    PRIMARY KEY (show_id, user_id)
);

-- ---------- idempotency keys ----------
-- Scoped per user. request_hash = hash(show_id + sorted seats), used to
-- detect "same key, different body". Inserted inside the booking transaction,
-- so a declined booking leaves no key behind and can be retried later.
CREATE TABLE idempotency_keys (
    user_id         TEXT        NOT NULL,
    idem_key        TEXT        NOT NULL,
    request_hash    TEXT        NOT NULL,
    reservation_id  UUID        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, idem_key),
    CONSTRAINT fk_idem_reservation FOREIGN KEY (reservation_id)
        REFERENCES reservations (id) DEFERRABLE INITIALLY DEFERRED
);
